name: Selenium Tests with BrowserStack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  browserstack-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'  # Enable pip caching

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set BrowserStack credentials
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          LENDARY_EMAIL: ${{ secrets.LENDARY_EMAIL }}
          LENDARY_PASSWORD: ${{ secrets.LENDARY_PASSWORD }}
        run: |
          echo "BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME" >> $GITHUB_ENV
          echo "BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY" >> $GITHUB_ENV
          echo "LENDARY_EMAIL=$LENDARY_EMAIL" >> $GITHUB_ENV
          echo "LENDARY_PASSWORD=$LENDARY_PASSWORD" >> $GITHUB_ENV

      - name: Start BrowserStack Local Tunnel
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: ${{ github.run_id }}  # Use workflow run ID as identifier
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: Run Selenium tests
        run: |
          python3 tests/test.py
        continue-on-error: false  # Stop workflow if tests fail
        env:
          PYTHONUNBUFFERED: 1  # Enable real-time logging

      - name: Stop BrowserStack Local Tunnel
        if: always()  # Ensure tunnel is stopped even if tests fail
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop

      - name: Upload test artifacts
        if: always()  # Upload logs even if tests fail
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            tests/logs/
            tests/screenshots/
            tests/reports/
          retention-days: 7