# name: Selenium Tests with BrowserStack

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   browserstack-tests:
#     name: 'BrowserStack Test'
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'
#           cache: 'pip'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Set BrowserStack Credentials
#         env:
#           BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
#           BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
#           LENDARY_EMAIL: ${{ secrets.LENDARY_EMAIL }}
#           LENDARY_PASSWORD: ${{ secrets.LENDARY_PASSWORD }}

#       - name: Run Selenium tests
#         run: |
#           python3 tests/unit/test_login.py
#         env:
#           PYTHONUNBUFFERED: 1

#       - name: Upload test artifacts (Optional)
#         if: always()
#         uses: actions/upload-artifact@v3
#         with:
#           name: test-results
#           path: tests/unit/logs/
#           retention-days: 7
name: Selenium Tests with BrowserStack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  browserstack-tests:
    name: 'BrowserStack Test'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set BrowserStack Credentials
        run: |
          echo "Setting BrowserStack credentials..."
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          LENDARY_EMAIL: ${{ secrets.LENDARY_EMAIL }}
          LENDARY_PASSWORD: ${{ secrets.LENDARY_PASSWORD }}

      - name: Run Selenium tests
        run: |
          python3 tests/unit/test_login.py
        env:
          PYTHONUNBUFFERED: 1

      - name: Upload test artifacts (Optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: /data/Lendary/Lendary_Website/logs
          retention-days: 7